### ISSUE TITLE
 Error while running script

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#1]
after starting I see an error, please help

[root@netbox-sync]# python3 netbox-sync.py 
2020-10-26 18:43:23,767 - INFO: Starting NetBox Sync
2020-10-26 18:43:23,768 - DEBUG: Using config file: /opt/netbox-sync/settings.ini
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.api_token = 4c8***
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.host_fqdn = netbox.domain.com
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.port = 443
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.disable_tls = True
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.validate_tls_certs = True
2020-10-26 18:43:23,768 - DEBUG: Config: netbox.prune_enabled = True
2020-10-26 18:43:23,769 - DEBUG: Config: netbox.prune_delay_in_days = 30
2020-10-26 18:43:23,769 - DEBUG: Config: netbox.default_netbox_result_limit = 200
2020-10-26 18:43:23,769 - DEBUG: Config: netbox.timeout = 30
2020-10-26 18:43:23,769 - DEBUG: Config: netbox.max_retry_attempts = 4
2020-10-26 18:43:23,769 - DEBUG: Created new Session for NetBox.
HTTPConnectionPool(host='netbox.domain.com', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1342ac2978>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by bb-Ricardo** [comment]
Hi,

Did you change the host name to your netbox instance?

THIS IS PRE ALPHA SOFTWARE. FOR TEST PURPOSES ONLY.

**Comment by SerhiiZahuba** [comment]
Did you change the host name to your netbox instance? - yes

**Comment by bb-Ricardo** [comment]
Ha, bug in default config. you have to set disable_tls to false or just uncomment it.

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/97263442-a83a8580-182b-11eb-844b-f950a26bf829.png)


[root@ netbox-sync]# cat settings.ini | grep tls
disable_tls = true
validate_tls_certs = true


It did not help

**Comment by bb-Ricardo** [comment]
Python requests says "Connection refused"!

you can test your connection by a simple curl call or `openssl s_client -connect netbox.yourhost.com:443`

**Comment by SerhiiZahuba** [comment]
socket: Bad file descriptor
connect: errno = 9

Yes, but I use the same settings for the old sync with netbox https://github.com/synackray/vcenter-netbox-sync and everything works there.

**Comment by bb-Ricardo** [comment]
Then you first need to find out why you can't get an TLS connection from your command line. Once this works you should be able to use this script.

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/97806642-619ebe00-1c65-11eb-8c42-cd0d4294c1d7.png)
Thanks. I added an ssl certificate to my site, made the settings (as in the screenshot), synchronization works.
I have two questions.
1)  INFO:Netbox-Sync:Creating new NetBox 'IP address' object: 192.168.110.130/24
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

there is such an error in the log - I understand that this is not critical?

2) After synchronization, a new site "vCenter: my-example" appeared. And all the servers on which the virtual machines were transferred to it.

![image](https://user-images.githubusercontent.com/36307887/97806764-e7226e00-1c65-11eb-8390-717d88702369.png)
![image](https://user-images.githubusercontent.com/36307887/97806807-251f9200-1c66-11eb-9e38-dde0d089ecff.png)

**Comment by bb-Ricardo** [comment]
Thank you so much for this extensive testing and reporting.

Updated the script. can you test with log level `DEBUG2` then you will see way more information..

**Comment by SerhiiZahuba** [comment]
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2020-11-08 10:25:03,184 - DEBUG2: Received HTTP Status 200.
Traceback (most recent call last):
  File "./netbox-sync.py", line 162, in <module>
    main()
  File "./netbox-sync.py", line 126, in main
    NB_handler.query_current_data(list(set(netbox_objects_to_query)))
  File "/opt/netbox-sync/module/netbox/connection.py", line 290, in query_current_data
    pickle.dump(nb_data.get("results"), open( f"cache/{nb_object_class.__name__}.cache", "wb" ) )
FileNotFoundError: [Errno 2] No such file or directory: 'cache/NBPlatforms.cache'

**Comment by bb-Ricardo** [comment]
Can you do a `mkdir cache` in the script directory?

**Comment by SerhiiZahuba** [comment]
after mkdir cache and 1-2 min processing



2020-11-08 11:47:20,024 - DEBUG2: Found 1:1 MAC address match for virtual NIC 'vNIC 1'
2020-11-08 11:47:20,024 - DEBUG2: Found 1:1 MAC address match for virtual NIC 'vNIC 2'
Traceback (most recent call last):
  File "./netbox-sync.py", line 162, in <module>
    main()
  File "./netbox-sync.py", line 137, in main
    source.apply()
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 287, in apply
    view_details.get("view_handler")(obj)
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 1147, in add_virtual_machine
    nic_object_dict = self.map_object_interfaces_to_current_interfaces(vm_object, nic_data)
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 489, in map_object_interfaces_to_current_interfaces
    current_object_interface_names.remove(grab(mathing_int, "data.name"))
ValueError: list.remove(x): x not in list

**Comment by bb-Ricardo** [comment]
Thank you. Will fix that tonight.

**Comment by bb-Ricardo** [comment]
Or you can just uncomment the problematic line #489, that should not be a problem

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/98467285-23614b80-21dd-11eb-93e9-4a31a3ad95f1.png)
Thanks. I removed line 489. Synchronization has ended.
There is a main problem, I have all virtual machines moved to the "Standalone ESXi Host" cluster. Previously, each virtual machine was in its own cluster.

**Comment by SerhiiZahuba** [comment]
I found two new bugs
1) when the interface (ip) is updated, it is not updated but added, that is, every time synchronization starts, I get +1 ip per interface
2) after the first successful update, I see an error in the log

Traceback (most recent call last):
  File "./netbox-sync.py", line 162, in <module>
    main ()
  File "./netbox-sync.py", line 149, in main
    inventory.set_primary_ips ()
  File "/opt/netbox-sync/module/netbox/inventory.py", line 474, in set_primary_ips
    object.update (data = {"primary_ip4": ip.nb_id})
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 280, in update
    self.updated_items.append (key)
AttributeError: 'dict_keys' object has no attribute 'append'

![image](https://user-images.githubusercontent.com/36307887/98468049-67564f80-21e1-11eb-8293-f826c97e0acb.png)

**Comment by bb-Ricardo** [comment]
1. Yes, this happens due to caching. Only added this to speed up testing. Remove all files in the cache folder and this should not happen again.

2. The primary ip part is not finished yet. Hopefully finish this tomorrow 

The Standalone ESXi issue is still strange. Will add some more debugging output to see what's going on.

**Comment by bb-Ricardo** [comment]
Hi, would you mind testing the lasted commit? Would be interested if all your VMs are still but on a "Standalone ESXi"

**Comment by SerhiiZahuba** [comment]
Hello, Thanks for new version.
I have an error after start



2020-11-14 07:05:33,913 - DEBUG: Config: netbox.default_netbox_result_limit = 200
2020-11-14 07:05:33,913 - DEBUG: Config: netbox.timeout = 30
2020-11-14 07:05:33,913 - DEBUG: Config: netbox.max_retry_attempts = 4
2020-11-14 07:05:33,913 - DEBUG: Created new requests Session for NetBox.
encoding with 'idna' codec failed (UnicodeError: label too long)

**Comment by bb-Ricardo** [comment]
Mmmhhh, This part hasn't changed afaik.
Did you change the config file?
It seems the encoding of the hostname in the config filw is nut UTF-8.

**Comment by SerhiiZahuba** [comment]
Sorry, I found my mistake, put a space at the beginning of the line. After I fixed my error, the script started, but after 2 minutes I see an error




2020-11-14 07:41:14,297 - INFO: Updating NetBox 'interface' object 'vmk1 (10.26.56.110)' with data: {'name': 'vmk1', 'type': 'virtual', 'mtu': 1500, 'mac_address': '00:50:56:6D:CC:CC', 'description': 'Management-VLAN78 (vSwitch0, vlan ID: 110)', 'mode': 'access', 'untagged_vlan': 55, 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}]}
2020-11-14 07:41:14,354 - ERROR: NetBox returned: PATCH /api/dcim/interfaces/274/?limit=200&exclude=config_context Bad Request
2020-11-14 07:41:14,354 - ERROR: NetBox returned body: {'untagged_vlan': ["VLAN ESXi Management-VLAN78 (ID: 110) (vCenter: my-example) (110) must belong to the same site as the interface's parent device, or it must be global."]}
2020-11-14 07:41:14,354 - ERROR: Request Failed for interface. Used data: {'name': 'vmk1', 'type': 'virtual', 'mtu': 1500, 'mac_address': '00:50:56:6D:CC:CC', 'description': 'Management-VLAN78 (vSwitch0, vlan ID: 110)', 'mode': 'access', 'untagged_vlan': 55, 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}]}
2020-11-14 07:41:14,354 - INFO: Updating NetBox 'interface' object 'vmnic0 (10.26.56.110)' with data: {'mode': 'tagged'}
Traceback (most recent call last):
  File "./netbox-sync.py", line 150, in <module>
    main()
  File "./netbox-sync.py", line 140, in main
    NB_handler.update_instance()
  File "/opt/netbox-sync/module/netbox/connection.py", line 564, in update_instance
    self.update_object(nb_object_sub_class)
  File "/opt/netbox-sync/module/netbox/connection.py", line 543, in update_object
    object.update(data=unresolved_dependency_data)
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 171, in update
    display_name = self.get_display_name(data)
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 323, in get_display_name
    raise ValueError(f"Unable to determine second key for {this_data_set.get(secondary_key)}")
ValueError: Unable to determine second key for None

**Comment by bb-Ricardo** [comment]
Hi, good point.

It should not fail like that. I will change the behavior if dependencies are unresolvable. This happens if the script wants to acces not existing objects.

On the NetBox errors: this is most likely caused due to a previous sync and the that now the name of the source has changed. If you change it back to the old name it should work.

On the other note: It is quite important to keep everything separated in different sites. A lot of object relations in NetBox depend on the site. For example you can have the same IP prefix in two different sites. But to find the correct IP prefix NetBox needs to know which site you mean.

By default the program creats a site like `vCenter: my-example` if nothing else is defined.

That's why it's important to set `cluster_site_relation` properly. A site shares IP prefixes, VRFs and VLANs.

Try to configure it and see if it's working then. Let me know if you need any advice.

Thank you so much for this extensive teating.

**Comment by SerhiiZahuba** [comment]
OK. Thanks for the information.
In cluster_site_relation and host_site_relation I have recorded all clusters. After your new commit, I'll try to run the sync again.

**Comment by bb-Ricardo** [comment]
It should work now already.

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/99143372-7fa4ef00-2665-11eb-9afd-a0521c945ae3.png)


I downloaded git again, but there is an error

**Comment by bb-Ricardo** [comment]
Sorry, just changed this bit. You might should delete the contents of the cache directory if there are any.

just do a `git pull`

**Comment by SerhiiZahuba** [comment]
2020-11-14 11:06:20,837 - ERROR: NetBox returned: POST /api/virtualization/interfaces/?limit=200&exclude=config_context Bad Request
2020-11-14 11:06:20,837 - ERROR: NetBox returned body: {'virtual_machine': ['This field is required.']}
2020-11-14 11:06:20,837 - ERROR: Request Failed for virtual machine interface. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}], 'name': 'vNIC 1', 'mac_address': '00:50:56:82:E3:A7', 'description': 'Network adapter 1 (VirtualVmxnet3)', 'enabled': False, 'mtu': 1500}
2020-11-14 11:06:20,837 - INFO: Updating NetBox 'interface' object 'vmk1 (10.26.56.110)' with data: {'name': 'vmk1', 'type': 'virtual', 'mtu': 1500, 'mac_address': '00:50:56:6D:CC:CC', 'description': 'Management-VLAN78 (vSwitch0, vlan ID: 110)', 'mode': 'access', 'untagged_vlan': 71, 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}]}
2020-11-14 11:06:20,898 - ERROR: NetBox returned: PATCH /api/dcim/interfaces/274/?limit=200&exclude=config_context Bad Request
2020-11-14 11:06:20,899 - ERROR: NetBox returned body: {'untagged_vlan': ["VLAN Management-VLAN78 (110) must belong to the same site as the interface's parent device, or it must be global."]}
2020-11-14 11:06:20,899 - ERROR: Request Failed for interface. Used data: {'name': 'vmk1', 'type': 'virtual', 'mtu': 1500, 'mac_address': '00:50:56:6D:CC:CC', 'description': 'Management-VLAN78 (vSwitch0, vlan ID: 110)', 'mode': 'access', 'untagged_vlan': 71, 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}]}
2020-11-14 11:06:20,899 - INFO: Updating NetBox 'interface' object 'vmnic0 (10.26.56.110)' with data: {'type': '1000base-t', 'mtu': 1500, 'description': '1Gb/s  pNIC (vSwitch0)', 'mode': 'tagged', 'tags': [{'name': 'Source: my-example'}, {'name': 'NetBox-synced'}, {'name': 'vcenter'}, {'name': 'vCenter'}]}
Traceback (most recent call last):
  File "./netbox-sync.py", line 150, in <module>
    main()
  File "./netbox-sync.py", line 140, in main
    NB_handler.update_instance()
  File "/opt/netbox-sync/module/netbox/connection.py", line 564, in update_instance
    self.update_object(nb_object_sub_class)
  File "/opt/netbox-sync/module/netbox/connection.py", line 543, in update_object
    object.update(data=unresolved_dependency_data)
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 171, in update
    display_name = self.get_display_name(data)
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 324, in get_display_name
    log.error(f"Unable to determine second key '{secondary_key}' for {self.name} '{name}', got: {org_secondary_key_value}")
NameError: name 'name' is not defined

**Comment by bb-Ricardo** [comment]
Do you mind sending me the log of a complete run (until failure) to mail mail address. Would need DEBUG2 as log level. Then I can have a look why your VMs are constantly assigned to the Standalone ESXi.

Will look at the ERROR again. Thank you

**Comment by bb-Ricardo** [comment]
Just pushed a fixed version

**Comment by SerhiiZahuba** [comment]
[netbox_sync.log](https://github.com/bb-Ricardo/netbox-sync/files/5540502/netbox_sync.log)

I didn't find your email, I attached it here, write when you download the log, I'll delete it later

**Comment by bb-Ricardo** [comment]
done

**Comment by bb-Ricardo** [comment]
On a quick glimpse I can't see any VM clusters or port group. Is this a permission problem or there aren't any?

And do you have just one ESXi in each location?

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/99147681-9100f200-268b-11eb-8224-bfea1061fca9.png)

I have multiple ESXIs on each site. One cluster = multiple VMs. One cluster = one ESXI. If you have the time and desire, you can connect to me through anydesk - I will show you everything.

**Comment by SerhiiZahuba** [comment]
strange but now synchronization ends with the word "Completed", but there are many errors in the logs
1) 2020-11-14 16: 11: 34,426 - INFO: Creating new NetBox 'interface' object 'vmk1 (192.168.110.110)' with data: {'tags': [{'name': 'NetBox-synced'} , {'name': 'Source: my-example'}], 'name': 'vmk1', 'mac_address': '00: 50: 56: 69: 86: 86 ',' mtu ': 1500,' description ':' s5_NFS_datastore (vSwitch1) ',' type ':' virtual ',' mode ':' access'}
2020-11-14 16: 11: 34,436 - ERROR: NetBox returned: POST / api / dcim / interfaces /? Limit = 2000 & exclude = config_context Bad Request
2020-11-14 16: 11: 34,436 - ERROR: NetBox returned body: {'device': ['This field is required.']}
2020-11-14 16: 11: 34,437 - ERROR: Request Failed for interface. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}], 'name': 'vmk1', 'mac_address': '00 : 50: 56: 69: 86: 86 ',' mtu ': 1500,' description ':' s5_NFS_datastore (vSwitch1) ',' type ':' virtual ',' mode ':' access'}

2) 2020-11-14 16: 11: 34,361 - ERROR: Unable to determine second key 'device' for interface 'None', got: None
2020-11-14 16: 11: 34,361 - ERROR: This could cause serious errors and lead to wrongly assigned object relations !!!
2020-11-14 16: 11: 34,361 - ERROR: Unable to determine second key 'device' for interface 'None', got: None
2020-11-14 16: 11: 34,362 - ERROR: This could cause serious errors and lead to wrongly assigned object relations !!!
2020-11-14 16: 11: 34,362 - ERROR: Unable to determine second key 'device' for interface 'None', got: None
2020-11-14 16: 11: 34,362 - ERROR: This could cause serious errors and lead to wrongly assigned object relations !!!
2020-11-14 16: 11: 34,363 - ERROR: Unable to determine second key 'device' for interface 'None', got: None
2020-11-14 16: 11: 34,363 - ERROR: This could cause serious errors and lead to wrongly assigned object relations !!!


3) all VMs in Standalone ESXi Host

4) 2020-11-14 16: 11: 34,815 - INFO: Updating NetBox 'IP address' object '192.168.110.13/24' with data: {'assigned_object_type': 'virtualization.vminterface'}
2020-11-14 16: 11: 34,899 - DEBUG: Ip address '192.168.110.13/24' attribute 'assigned_object_id' changed from '412' to 'vNIC 2 (C .... TC is one of the VM)' but in netbox this Vm and ip did not appear

**Comment by bb-Ricardo** [comment]
I had a look at your log and found that this "Standalone ESXi" is completely useless.
There a few things I have to change. 

on the other note: the site_relation option is a regex search, you could use it like this: `192\.168\.20\..* = XYZ`. This way all hosts which start with this name get site XYZ assigned.

**Comment by bb-Ricardo** [comment]
Hi,

I changed the code to reflect your setup. Can you give it a go and see if it works better?

Thank you

**Comment by SerhiiZahuba** [comment]
Super. Thank you very much. That helped. 99% of VMs have moved to their clusters. I see that only virtual machines with mikrotik did not move, I found only that VMware Tools are not installed on these VMs (there is no way to install it there). Otherwise, everything is super.

**Comment by bb-Ricardo** [comment]
Wow, great, happy to hear that.

Now I just need to document everything 😭

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/99266682-b3ca0c80-282b-11eb-81c4-1072ec23ba7a.png)
![image](https://user-images.githubusercontent.com/36307887/99266757-cba19080-282b-11eb-9b10-6c7d17ee43d7.png)

Documentation is awesome.
One more question, please look at my screenshots, where does synchronization take another interface vmk0 and why does it assign an ip?

**Comment by bb-Ricardo** [comment]
> ![image](https://user-images.githubusercontent.com/36307887/99266682-b3ca0c80-282b-11eb-81c4-1072ec23ba7a.png)
> ![image](https://user-images.githubusercontent.com/36307887/99266757-cba19080-282b-11eb-9b10-6c7d17ee43d7.png)
> 
> Documentation is awesome.
> One more question, please look at my screenshots, where does synchronization take another interface vmk0 and why does it assign an ip?

Check "VMKernel" adapter
