### ISSUE TITLE
Trying to find {object_type.name} based on serial number

### ISSUE THREAD

**Issue by WaaZaa666** [bb-Ricardo/netbox-sync#15]
I'm trying to setup this sync tool. Unforfunately running into an issue. 

- Netbox: 2.9.8
- vCenter 7.0.1.

When running the sync, it hangs on the following: 
2020-11-23 15:46:13,931 - DEBUG: vCenter returned '7' hosts
2020-11-23 15:46:13,932 - DEBUG2: Parsing vCenter host: esxi007.infra.domain.com
2020-11-23 15:46:13,936 - DEBUG2: Trying to find site name for device 'esxi007.infra.domain.com'
2020-11-23 15:46:13,936 - DEBUG2: Found a matching cluster site for esxi007.infra.domain.com, using site 'SITE1'
2020-11-23 15:46:15,239 - DEBUG2: Found host proxySwitch Compute01-VDS
2020-11-23 15:46:16,350 - DEBUG2: Parsing PhysicalNic: vmnic0
2020-11-23 15:46:16,350 - DEBUG2: Parsing PhysicalNic: vmnic1
2020-11-23 15:46:16,350 - DEBUG2: Parsing PhysicalNic: vmnic2
2020-11-23 15:46:16,350 - DEBUG2: Parsing PhysicalNic: vmnic3
2020-11-23 15:46:16,351 - DEBUG2: Parsing PhysicalNic: vmnic4
2020-11-23 15:46:16,351 - DEBUG2: Parsing PhysicalNic: vmnic5
2020-11-23 15:46:16,906 - DEBUG2: Parsing HostVirtualNic: vmk0
2020-11-23 15:46:16,907 - DEBUG: IP address 'fe80::eef4:bbff:fec8:15f8/64' for vmk0 is a link local address. Skipping.
2020-11-23 15:46:16,907 - DEBUG2: Parsing HostVirtualNic: vmk1
2020-11-23 15:46:16,907 - DEBUG: IP address 'fe80::250:56ff:fe6f:3647/64' for vmk1 is a link local address. Skipping.
2020-11-23 15:46:16,907 - DEBUG2: Trying to find a device based on the collected name, cluster, IP and MAC addresses
2020-11-23 15:46:16,908 - DEBUG2: No exact match found. Trying to find device based on MAC addresses
2020-11-23 15:46:16,908 - DEBUG2: No match found. Trying to find {object_type.name} based on serial number
Traceback (most recent call last):
  File "./netbox-sync.py", line 143, in <module>
    main()
  File "./netbox-sync.py", line 119, in main
    source.apply()
  File "/appl/netbox-sync/module/sources/vmware/connection.py", line 365, in apply
    view_details.get("view_handler")(obj)
  File "/appl/netbox-sync/module/sources/vmware/connection.py", line 1583, in add_host
    p_ipv4=host_primary_ip4, p_ipv6=host_primary_ip6)
  File "/appl/netbox-sync/module/sources/vmware/connection.py", line 891, in add_device_vm_to_inventory
    device_vm_object = self.get_by_data(object_type, data={"serial": object_data.get("serial")})
AttributeError: 'VMWareHandler' object has no attribute 'get_by_data'

Any pointers here? 

Thanks!

**Comment by bb-Ricardo** [comment]
Hi,

I just pushed a fix. Can you do a `git pull` again?

**Comment by WaaZaa666** [comment]
Holy cow, thats a quicker and better response than suppliers we actually pay deliver..

This seems to have fixed all my syncing issues at a first glance :D

**Comment by WaaZaa666** [comment]
And yep, all seems well. Thanks a lot!

**Comment by bb-Ricardo** [comment]
Just happened to be sitting right in front of it.
