### ISSUE TITLE
Recreate expired vCenter sessions during long sync runs

### ISSUE THREAD

**Issue by ncansado** [bb-Ricardo/netbox-sync#188]
Hi,
 my problem scenario is that I've several vcenters.
 If  I run the tool vcenter by vcenter, it runs ok, but if I configure all vcenters in one call, it fails after 30 min.

Currently if i've one config per vcenter it will run ok but purges the previous runs (required to purge every time)
The goal is to run all vcenters in a row.

I noticed that the tool perform the connnection to all vcenters at begin. I tyhink the problem would go away if calls are done 1 at time.
This is the error that i got after 30min,( I know that is timeout related with vcenter session on idle).

- ERROR: Problem creating venter view for 'networks': (vim.fault.NotAuthenticated)
dynamicType = ‹unset>,
dynamicProperty = (vmodl. DynamicProperty)
01
msg = 'The session is not authenticated.
faultCause = ‹unset>,
faultMessage = (vmodl. LocalizableMessage) (l,
object =
"vim. Folder: group-dl',
privileged = 'System.View!

Help would be appreciated.

PS. I really like the outcome of this tool, really good work

**Comment by bb-Ricardo** [comment]
Hi,

Yes indeed, I heaven't thought of that.
If the session (created at the beginning) has expired by the time the script reached this vCenter then the request will fail.

Just need to add a validation to check if the session is still active. And create a new session in that case.

The check at the beginning is used to validate the connectivity and credentials and fail early to let the user know that something is not correct.

Will add this to the next version. Thank you

**Comment by bb-Ricardo** [comment]
Hi @ncansado,

I just pushed a fix for this to the "development" branch. Can you switch to this branch and see if it fixes the the issue?

Thank you

**Comment by akurach** [comment]
this fix broke connection ( for me) 
`➜  netbox-sync git:(development) ✗ ./netbox-sync.py -c settings-vcname.ini
2022-05-19 13:03:30,938 - INFO: Starting NetBox Sync v1.2.3 (2022-04-09)
2022-05-19 13:03:31,101 - INFO: Successfully connected to NetBox 'netbox'
2022-05-19 13:03:31,102 - INFO: Initializing sources
2022-05-19 13:03:31,286 - INFO: Successfully connected to vCenter SDK 'vcname'
2022-05-19 13:03:31,287 - INFO: Querying necessary objects from NetBox. This might take a while.
2022-05-19 13:03:40,690 - INFO: Finished querying necessary objects from NetBox
2022-05-19 13:03:41,093 - INFO: Query data from vCenter: 'vcname'
Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 121, in main
    source.apply()
  File "/Users/avkurach/git/Netbox-sync-test/netbox-sync/module/sources/vmware/connection.py", line 464, in apply
    self.session.sessionManager.sessionList
  File "/Users/avkurach/Library/Python/3.8/lib/python/site-packages/pyVmomi/VmomiSupport.py", line 700, in __call__
    return self.f(*args, **kwargs)
  File "/Users/avkurach/Library/Python/3.8/lib/python/site-packages/pyVmomi/VmomiSupport.py", line 520, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/Users/avkurach/Library/Python/3.8/lib/python/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'Sessions.TerminateSession'
}`


previous version has no permission problems, any ideas?

**Comment by ncansado-au** [comment]
Hi Ricardo,
Thanks for quick reply, but I also got these errors with the development branch



2022-05-19 21:33:46,483 - INFO: Skipping offline VMs
Traceback (most recent call last):
  File "/opt/netbox_plugin/netbox-sync/tmp/netbox-sync/./netbox-sync.py", line 145, in <module>
    main()
  File "/opt/netbox_plugin/netbox-sync/tmp/netbox-sync/./netbox-sync.py", line 121, in main
    source.apply()
  File "/opt/netbox_plugin/netbox-sync/tmp/netbox-sync/module/sources/vmware/connection.py", line 464, in apply
    self.session.sessionManager.sessionList
  File "/opt/netbox-3.2.2/venv/lib64/python3.9/site-packages/pyVmomi/VmomiSupport.py", line 700, in __call__
    return self.f(*args, **kwargs)
  File "/opt/netbox-3.2.2/venv/lib64/python3.9/site-packages/pyVmomi/VmomiSupport.py", line 520, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/opt/netbox-3.2.2/venv/lib64/python3.9/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'Sessions.TerminateSession'
}

**Comment by bb-Ricardo** [comment]
Thank you for testing. I will try another attribute.

**Comment by bb-Ricardo** [comment]
Hi @akurach , @ncansado-au, @ncansado 

I pushed another change. Can you test if it works with this setting?

Thank you

**Comment by akurach** [comment]
@bb-Ricardo works!

**Comment by ncansado** [comment]
@bb-Ricardo it works!
Plus I see new custom fields getting updated !

thanks!

N

**Comment by bb-Ricardo** [comment]
@ncansado 

That is great.

So now you have all sources in one config file?

If ao there should be an INFO message about session expire in your log. Can you please have a look?

Thank you

**Comment by ncansado** [comment]
hi @bb-Ricardo ,

these are the messages 
INFO: No existing Center session found.
INFO: Successfully connected to venter API

these are the messages that you expected ?
 it  works!

N

**Comment by bb-Ricardo** [comment]
Yes, that's it. Thank you very much.
