### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__name__'

### ISSUE THREAD

**Issue by vfit-pwl** [bb-Ricardo/netbox-sync#194]
2022-05-26 13:01:22,045 - INFO: Initializing sources
2022-05-26 13:01:22,137 - INFO: Successfully connected to vCenter SDK 'vcenter.local'
2022-05-26 13:01:22,137 - INFO: Querying necessary objects from NetBox. This might take a while.
2022-05-26 13:01:24,556 - INFO: Finished querying necessary objects from NetBox
Traceback (most recent call last):
  File "/opt/netbox-sync/./netbox-sync.py", line 145, in <module>
    main()
  File "/opt/netbox-sync/./netbox-sync.py", line 113, in main
    inventory.resolve_relations()
  File "/opt/netbox-sync/module/netbox/inventory.py", line 216, in resolve_relations
    this_object.resolve_relations()
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 1554, in resolve_relations
    self.data["assigned_object_id"] = self.inventory.get_by_id(self.data_model_relation.get(o_type), nb_id=o_id)
  File "/opt/netbox-sync/module/netbox/inventory.py", line 62, in get_by_id
    (object_type.__name__, NetBoxObject.__name__))
AttributeError: 'NoneType' object has no attribute '__name__'

**Comment by bb-Ricardo** [comment]
Hi, can you try out the latest "development" branch? It should be fixed there.

Thank you.

**Comment by vfit-pwl** [comment]
> Hi, can you try out the latest "development" branch? It should be fixed there.
> 
> Thank you.


Thank you. 👍
