### ISSUE TITLE
add an exclude option to permitted subnets to exclude small chunks of a bit block

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/netbox-sync#203]
exclude subnets with a leading `!`
suggestion:
```ini
permitted_subnets = 172.16.0.0/12, 10.0.0.0/8, !10.8.0.0/24
```

**Comment by Eldiabolo21** [comment]
This seems to lead to a problem for me:
```
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:26,932 - INFO: Finished querying necessary objects from NetBox
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:26,932 - DEBUG: Start resolving relations
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:29,744 - DEBUG: Finished resolving relations
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:29,744 - DEBUG: Checking/Adding NetBox Sync dependencies
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:29,744 - DEBUG: Retrieving data from source 'my-redfish-example'
netbox-sync-netbox-syncer-1  | 2022-11-23 07:59:29,760 - DEBUG: Parsing inventory file /scripts/volume/redfish-inventory/bmc-srv010903.syseleven.net.json
netbox-sync-netbox-syncer-1  | Traceback (most recent call last):
netbox-sync-netbox-syncer-1  |   File "/netbox-sync/./netbox-sync.py", line 145, in <module>
netbox-sync-netbox-syncer-1  |     main()
netbox-sync-netbox-syncer-1  |   File "/netbox-sync/./netbox-sync.py", line 121, in main
netbox-sync-netbox-syncer-1  |     source.apply()
netbox-sync-netbox-syncer-1  |   File "/netbox-sync/module/sources/check_redfish/import_inventory.py", line 242, in apply
netbox-sync-netbox-syncer-1  |     self.update_network_interface()
netbox-sync-netbox-syncer-1  |   File "/netbox-sync/module/sources/check_redfish/import_inventory.py", line 852, in update_network_interface
netbox-sync-netbox-syncer-1  |     excluded_subnets=self.excluded_subnets, interface_name=port_name) is False:
netbox-sync-netbox-syncer-1  | AttributeError: 'CheckRedfish' object has no attribute 'excluded_subnets'. Did you mean: 'permitted_subnets'?
netbox-sync-netbox-syncer-1 exited with code 1
```

Weirdly enough, this only happens in a containerized version, when running in a venv ony my mac, it works flawless.

**Comment by bb-Ricardo** [comment]
Mhh, which python version are you running in your venv and which one in your docker container?

**Comment by Eldiabolo21** [comment]
Container (which throws the error) has `Python 3.10.6`, local install has `Python 3.10.8`

**Comment by bb-Ricardo** [comment]
very strange, actually no idea why there would be such a difference in behaviour between these two environments

**Comment by Eldiabolo21** [comment]
What do you suggest? I'm pretty sure this feature is the cause, if I check out the commit before this commit, it works.

**Comment by bb-Ricardo** [comment]
Hi,

I just pushed another commit. I'm certain I found the issue. Can you check out the latest `development` branch and see if it works?

Thank you

**Comment by Eldiabolo21** [comment]
Unfortunately still the issue, I'm sure i checked out the latest commit from the development branch.
```
netbox_syncer  | 2022-12-05 12:11:38,387 - INFO: Finished querying necessary objects from NetBox
netbox_syncer  | 2022-12-05 12:11:38,387 - DEBUG: Start resolving relations
netbox_syncer  | 2022-12-05 12:11:41,556 - DEBUG: Finished resolving relations
netbox_syncer  | 2022-12-05 12:11:41,556 - DEBUG: Checking/Adding NetBox Sync dependencies
netbox_syncer  | 2022-12-05 12:11:41,556 - DEBUG: Retrieving data from source 'my-redfish-example'
netbox_syncer  | 2022-12-05 12:11:41,581 - DEBUG: Parsing inventory file /scripts/volume/redfish-inventory/bmc-srv010903.syseleven.net.json
netbox_syncer  | 2022-12-05 12:11:41,620 - INFO: Created new power port object: Power Supply 1 (231V AC)
netbox_syncer  | 2022-12-05 12:11:41,620 - INFO: Created new power port object: Power Supply 2 (231V AC)
netbox_syncer  | Traceback (most recent call last):
netbox_syncer  |   File "/scripts/netbox-sync/./netbox-sync.py", line 153, in <module>
netbox_syncer  |     main()
netbox_syncer  |   File "/scripts/netbox-sync/./netbox-sync.py", line 121, in main
netbox_syncer  |     source.apply()
netbox_syncer  |   File "/scripts/netbox-sync/module/sources/check_redfish/import_inventory.py", line 242, in apply
netbox_syncer  |     self.update_network_interface()
netbox_syncer  |   File "/scripts/netbox-sync/module/sources/check_redfish/import_inventory.py", line 863, in update_network_interface
netbox_syncer  |     excluded_subnets=self.excluded_subnets, interface_name=port_name) is False:
netbox_syncer  | AttributeError: 'CheckRedfish' object has no attribute 'excluded_subnets'. Did you mean: 'permitted_subnets'?
netbox_syncer exited with code 1
```

**Comment by bb-Ricardo** [comment]
Hi, did you pull the latest container or did you build a new container from the source and used this one?

**Comment by bb-Ricardo** [comment]
mmhhh, I pushed another commit. Could you try this one again? thank you

**Comment by Eldiabolo21** [comment]
wheee 👍 , works this time. 

One thing I noticed and where i'm not sure if this is related to the code changes in this issue or if it is something independent:
The PSUs now get created with the current Input-Voltage, which looks really weird and creates lots of different PSUs:
```
netbox_syncer  | 2022-12-05 23:07:58,728 - INFO: Created new power port object: Power Supply 1 (229V AC)
netbox_syncer  | 2022-12-05 23:07:58,728 - INFO: Created new power port object: Power Supply 2 (229V AC)
[...]
netbox_syncer  | 2022-12-05 23:07:59,052 - INFO: Created new power port object: Power Supply 1 (228V AC)
netbox_syncer  | 2022-12-05 23:07:59,052 - INFO: Created new power port object: Power Supply 2 (230V AC)
[...]
netbox_syncer  | 2022-12-05 23:07:59,374 - INFO: Created new power port object: Power Supply 1 (229V AC)
netbox_syncer  | 2022-12-05 23:07:59,374 - INFO: Created new power port object: Power Supply 2 (231V AC)
[...]
netbox_syncer  | 2022-12-05 23:07:59,689 - INFO: Created new power port object: Power Supply 1 (232V AC)
netbox_syncer  | 2022-12-05 23:07:59,689 - INFO: Created new power port object: Power Supply 2 (227V AC)
```

**Comment by bb-Ricardo** [comment]
Great to hear.

Will have a look into ps naming tomorrow.
