### ISSUE TITLE
minor issue with final reporting by the end of netbox-sync execution

### ISSUE THREAD

**Issue by hikarikumo** [bb-Ricardo/netbox-sync#248]
Hello! Thanks a lot for a nice software.
When netbox-sync got up and running for more than a day the final report should corrected:

```
2022-10-18 01:03:25,587 - ERROR: Unfortunately updated item assigned_object_id for object 10.129.1.196/24 could not be fully resolved: <NBVMInterface instance 'vNIC 2 (AMS-1202) (veeam-test-02)' at 140638424179992>
2022-10-18 01:03:25,587 - INFO: Pruning orphaned data in NetBox
Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 141, in main
    log.info("Completed NetBox Sync in %s" % get_relative_time(datetime.now() - start_time))
  File "/home/vladimir.vasilenko/git/netbox-sync/module/common/misc.py", line 139, in get_relative_time
    parts = [float(x) for x in str(delta).split(":")]
  File "/home/vladimir.vasilenko/git/netbox-sync/module/common/misc.py", line 139, in <listcomp>
    parts = [float(x) for x in str(delta).split(":")]
ValueError: could not convert string to float: '2 days, 3'
```

**Comment by bb-Ricardo** [comment]
Hi, The script was running for 2 days? Wow. Was not anticipating this. Have to look into fixing this long run output 😄

**Comment by bb-Ricardo** [comment]
Hi, I pushed a fix for both issues to the `development` branch

**Comment by bb-Ricardo** [comment]
consider this issue as resolved
