### ISSUE TITLE
Purge exits with Error

### ISSUE THREAD

**Issue by HarishankarYellapragada** [bb-Ricardo/netbox-sync#251]
```
./netbox-sync.py -p
2022-10-30 16:55:33,991 - INFO: Starting NetBox Sync v1.3.0 (2022-09-06)
2022-10-30 16:55:35,983 - INFO: Successfully connected to NetBox '0.0.0.0'
2022-10-30 16:55:35,983 - INFO: Querying necessary objects from NetBox. This might take a while.
2022-10-30 16:55:56,274 - INFO: Finished querying necessary objects from NetBox
2022-10-30 16:55:56,443 - WARNING: Starting purge now. All objects with the tag 'NetBox-synced' will be deleted!!!
2022-10-30 16:55:56,444 - INFO: IP address '0.0.0.0/0' will be deleted now
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 91, in main
    nb_handler.just_delete_all_the_things()
  File "/opt/netbox-sync/module/netbox/connection.py", line 887, in just_delete_all_the_things
    result = self.request(nb_object_sub_class, req_type="DELETE", nb_id=this_object.nb_id)
  File "/opt/netbox-sync/module/netbox/connection.py", line 315, in request
    result = response.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```
Removed IP addresses for security purposes and replaced them with 0.0.0.0

**Comment by bb-Ricardo** [comment]
fixed in 'next-release' branch
