### ISSUE TITLE
Script fails in netbox v3.3.9 

### ISSUE THREAD

**Issue by HarishankarYellapragada** [bb-Ricardo/netbox-sync#262]
```
2022-12-13 13:36:48,646 - INFO: Starting NetBox Sync v1.3.0 (2022-09-06) 
2022-12-13 13:36:48,688 - INFO: Successfully connected to NetBox 'x.x.x.x' 
2022-12-13 13:36:48,689 - INFO: Initializing sources 
2022-12-13 13:36:48,792 - INFO: Successfully connected to vCenter SDK 'vcenter.abc.com' 
2022-12-13 13:36:50,219 - INFO: Successfully connected to vCenter SDK 'vcenter.xyz.com' 
2022-12-13 13:36:50,220 - INFO: Querying necessary objects from NetBox. This might take a while. 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json 
    return complexjson.loads(self.text, **kwargs) 
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads 
    return _default_decoder.decode(s) 
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode 
    obj, end = self.raw_decode(s) 
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode 
    return self.scan_once(s, idx=_w(s, idx).end()) 
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1) 

During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
  File "netbox-sync.py", line 145, in <module> 
    main() 
  File "netbox-sync.py", line 108, in main 
    nb_handler.query_current_data(source.dependent_netbox_objects) 
  File "path of the file", line 505, in query_current_data 
    full_nb_data = self.request(nb_object_class) 
  File "path of the file", line 328, in request 
    result["results"].extend(response.json().get("results")) 
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 917, in json 
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) 
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <title>Server</title> 
    <link rel="stylesheet" href="/static/netbox-light.css" /> 
    <meta charset="UTF-8"> 
</head> 
<body> 
    <div class="container-fluid"> 
        <div class="row"> 
            <div class="col col-md-6 offset-md-3"> 
                <div class="card border-danger mt-5"> 
                    <h5 class="card-header"> 
                        <i class="mdi mdi-alert"></i> Server 
                    </h5> 
                    <div class="card-body"> 
 
                            <p> 
                                There was a problem with your request. Please contact an administrator. 
                            </p> 
 
                        <hr /> 
                        <p> 
                            The complete exception is provided below: 
                        </p> 
<pre class="block"><strong>&lt;class &#x27;Ke&#x27;&gt;</strong><br /> 
&#x27;decomissioned&#x27; 
Python version: 3.10.6 
NetBox version: 3.3.9</pre> 
                        <p> 
                            If further assistance is required, please post to the <a href="https://github.com/netbox-community/netbox/discussions">NetBox discussion forum</a> on GitHub. 
                        </p> 
                        <div class="text-end"> 
                            <a href="/" class="btn btn-primary">Home Page</a> 
                        </div> 
                    </div> 
                </div> 
            </div> 
        </div> 
    </div> 
</body> 
</html> 
: 1 
The remote script failed with exit code 1 
The action netbox-sync scheduled on a Worker failed 
```
Script was running fine on previous version. 
The user and token still exists.

**Comment by HarishankarYellapragada** [comment]
Issue got resolved as custom field is missing in new version config file
