### ISSUE TITLE
VMware sync: Multiple ESXi hosts not added correctly.

### ISSUE THREAD

**Issue by vkernelblog** [bb-Ricardo/netbox-sync#263]
Hi,

What a great tool to sync a vCenter inventory into Netbox! 
I have only one problem with the VMware sync. 
Every first ESXi node of the cluster is added into Netbox but the ESXI hosts after are updating the first host. 

See the log files:

2022-12-14 13:47:23,696 - DEBUG: Parsing vCenter host: alm-esx02.vkernel.lan
2022-12-14 13:47:23,700 - DEBUG2: Trying to find site name for device 'alm-esx02.vkernel.lan'
2022-12-14 13:47:23,700 - DEBUG2: Found a matching cluster site for alm-esx02.vkernel.lan, using site 'vCenter: alm-vc01.vkernel.lan'
2022-12-14 13:47:24,415 - DEBUG2: Found a matching device object: alm-esx01.vkernel.lan (vCenter: alm-vc01.vkernel.lan)
2022-12-14 13:47:24,415 - DEBUG2: Parsing 'device' data structure: alm-esx02.vkernel.lan
2022-12-14 13:47:24,415 - INFO: Device 'alm-esx02.vkernel.lan' attribute 'name' changed from 'alm-esx01.vkernel.lan' to 'alm-esx02.vkernel.lan'
2022-12-14 13:47:24,415 - DEBUG: Updated device object: alm-esx02.vkernel.lan
2022-12-14 13:47:24,415 - DEBUG2: Parsing 'device' data structure: alm-esx02.vkernel.lan
2022-12-14 13:47:24,416 - DEBUG2: Found '6' NICs in NetBox for 'alm-esx02.vkernel.lan'
2022-12-14 13:47:24,416 - DEBUG2: Parsing 'interface' data structure: vmnic0 (alm-esx02.vkernel.lan)

This happens for every cluster.

**Comment by bb-Ricardo** [comment]
Hi,

Is it possible that all machines are using the same asset_tag or same serial (Blade Server).

Then you need to disable sync of these attributes in the config.

**Comment by vkernelblog** [comment]
Hi Ricardo,

You are right. They have the same serial number and asset tag.
I tried with the following setting in the config, but same issue:
match_host_by_serial = False

(I even manually removed all the records in netbox and rerun the script.)

Also. the purge option isn't working for me.

(.venv) root@alm-ipam01:/opt/netbox-sync# python3 netbox-sync.py -p
2022-12-15 10:04:37,897 - INFO: Starting NetBox Sync v1.3.0 (2022-09-06)
2022-12-15 10:04:37,909 - INFO: Successfully connected to NetBox 'alm-ipam01.vkernel.lan'
2022-12-15 10:04:37,909 - INFO: Querying necessary objects from NetBox. This might take a while.
2022-12-15 10:04:38,421 - ERROR: NetBox returned: GET /api//ipam/fhrp-groups/?limit=200&exclude=config_context Not Found
2022-12-15 10:04:38,421 - ERROR: NetBox returned body: None
Traceback (most recent call last):
  File "/opt/netbox-sync/netbox-sync.py", line 145, in <module>
    main()
  File "/opt/netbox-sync/netbox-sync.py", line 91, in main
    nb_handler.just_delete_all_the_things()
  File "/opt/netbox-sync/module/netbox/connection.py", line 854, in just_delete_all_the_things
    self.query_current_data(NetBoxObject.__subclasses__())
  File "/opt/netbox-sync/module/netbox/connection.py", line 507, in query_current_data
    if full_nb_data.get("results") is None:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bb-Ricardo** [comment]
Hi,

Can you try the `next-release` branch for purging?

and if you switch off the `collect_hardware_asset_tag` option?

**Comment by vkernelblog** [comment]
Hi,

It works fine now with the followings settings:

match_host_by_serial = False
collect_hardware_asset_tag = False

How can i try the next-release, do you have a .git link for me?

Thanks

**Comment by bb-Ricardo** [comment]
in the git repository you just need to do a `git checkout next-release` and then you are on the development branch

**Comment by bb-Ricardo** [comment]
will close this issue as it seems to be resolved.
