### ISSUE TITLE
Issue with empty vCenter tags

### ISSUE THREAD

**Issue by Alpha-Dan** [bb-Ricardo/netbox-sync#290]
Hi,

How import VM tags in tenant or other field in netbox ? 
I check others issues but i don't see any variable in settings.ini.

Regards

**Comment by bb-Ricardo** [comment]
Hi,

I'm not sure what exactly you are trying to do. Can you add a detailed description of what you are trying to achieve?

**Comment by Alpha-Dan** [comment]
In my vcenter, on VM I have some tags:
![image](https://user-images.githubusercontent.com/68696409/230337589-d86c0cb8-84d2-4cb8-8883-bec0351a99ba.png)

I want to sync the tags into netbox in custom field or tenant for exemple.

regards

**Comment by bb-Ricardo** [comment]
Hi,

have you tried this?:
https://github.com/bb-Ricardo/netbox-sync/blob/20e3a3c2ff2925e9e88ff4dcb39d0c3c589d0d48/settings-example.ini#L278-L291

**Comment by Alpha-Dan** [comment]
Hi,

I try to add 

`vm_tag_source = object`

but The script return an error:

`2023-04-07 12:36:15,085 - INFO: Created new tag object: None
2023-04-07 12:36:15,302 - ERROR: This 'tag' data structure does not contain the primary key 'name' got: {'name': None}
2023-04-07 12:36:15,302 - INFO: Virtual machine 'XXXXXXXXXX' attribute 'comments' changed from '' to 'None'
Traceback (most recent call last):
  File "/app/netbox-sync.py", line 143, in <module>
    main()
  File "/app/netbox-sync.py", line 111, in main
    source.apply()
  File "/app/module/sources/vmware/connection.py", line 393, in apply
    view_details.get("view_handler")(obj)
  File "/app/module/sources/vmware/connection.py", line 2363, in add_virtual_machine
    self.add_device_vm_to_inventory(NBVM, object_data=vm_data, vnic_data=nic_data,
  File "/app/module/sources/vmware/connection.py", line 1056, in add_device_vm_to_inventory
    device_vm_object.update(data=object_data, source=self)
  File "/app/module/netbox/object_classes.py", line 590, in update
    new_value_str = str(new_value.get_display_name())
  File "/app/module/netbox/object_classes.py", line 1101, in get_display_name
    return sorted([x.get_display_name() for x in self])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
(.venv) root@dcimvmware:/opt/netbox-sync#
`

I use this command to start up the script:

`docker run --rm -it -v $(pwd)/settings.ini:/app/settings.ini bbricardo/netbox-sync:latest`

**Comment by bb-Ricardo** [comment]
this looks like a bug and should be fixed. Will look into it.

**Comment by bb-Ricardo** [comment]
Hi @Alpha-Dan:

I just pushed a new commit to `development` branch to fix this issue. Can you try it out and see if it's working now?

**Comment by bb-Ricardo** [comment]
closing this as fixed
