### ISSUE TITLE
Error while requesting virtual machines

### ISSUE THREAD

**Issue by liudasdd** [bb-Ricardo/netbox-sync#3]
Hi, 

You are doing great job! But I had following error: 

2020-11-08 15:05:36,995 - DEBUG: Created new requests Session for NetBox.
2020-11-08 15:05:37,030 - INFO: Successfully connected to NetBox '10.X.X.44'
2020-11-08 15:05:37,030 - DEBUG: Detected NetBox API version: 2.9
2020-11-08 15:05:37,030 - INFO: Initializing sources
<..>
2020-11-08 15:05:37,144 - INFO: Successfully connected to vCenter '10.X.X.253'
2020-11-08 15:05:37,145 - INFO: Querying necessary objects from Netbox. This might take a while.
2020-11-08 15:05:37,145 - DEBUG: Requesting virtual machines from NetBox
2020-11-08 15:05:37,244 - DEBUG2: Received HTTP Status 200.

Traceback (most recent call last):
  File "netbox-sync.py", line 162, in <module>
    main()
  File "netbox-sync.py", line 126, in main
    NB_handler.query_current_data(list(set(netbox_objects_to_query)))
  File "/opt/netbox-sync/module/netbox/connection.py", line 290, in query_current_data
    pickle.dump(nb_data.get("results"), open( f"cache/{nb_object_class.__name__}.cache", "wb" ) )
FileNotFoundError: [Errno 2] No such file or directory: 'cache/NBVMs.cache'

So I've created "cache" directory and started to work. Adding this directory to the git would prevent error to other people

**Comment by bb-Ricardo** [comment]
Hi, thank you for taking the time to test.

It was more a mistake. I forgot to deactivate the cache option before pushing it out. Cache was only meant to speed up testing 😁. Was thinking to add it permanently but needs testing if NetBox supports queries which return objects based on the last creation/change date.

Once you synced the objects let me know about missing/wrong infos in NetBox.

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a new commit which should be the first working beta. can you give it a go please and let me know about any issues/errors?

thank you.

**Comment by liudasdd** [comment]
Hi, first run was successful. I did not get any errors from runtime. Good job

**Comment by bb-Ricardo** [comment]
Did you get any warnings? Did all VMs, VLANs, Prefix got synced/assigned properly?

**Comment by bb-Ricardo** [comment]
Can you test the "main" branch again please.

thank you.

**Comment by liudasdd** [comment]
Hi, after pulling the main branch:

Run log contains some errors:

2020-11-19 14:33:48,865 - ERROR: Unable to determine second key 'device' for interface '10.128.XX.1', got: None
2020-11-19 14:33:48,865 - ERROR: This could cause serious errors and lead to wrongly assigned object relations!!!

<..>

2020-11-19 14:33:50,462 - ERROR: NetBox returned: POST /api/ipam/vlans/ Bad Request
2020-11-19 14:33:50,462 - ERROR: NetBox returned body: {'vid': ['Ensure this value is greater than or equal to 1.']}
2020-11-19 14:33:50,462 - ERROR: Request Failed for VLAN. Used data: {'name': 'Management Network', 'vid': 0, 'site': 1}
2020-11-19 14:33:50,497 - ERROR: Unfortunately updated item tagged_vlans for object vmnic0 (10.128.XX.1) could not be fully resolved: [<NBVLAN instance '0 (YYY lab)' at 140469594168960>]

**Comment by bb-Ricardo** [comment]
This should not be happening. 😁 

Can you pull and run it again with `-l DEBUG2` option? I would need the output around the lines where vmnic0 of this host is parsed. VLAN 0 should result in no vlan assignment. But maybe it is a configuration I didn't consider.

Thank you

**Comment by bb-Ricardo** [comment]
I found the error and fixed the VLAN ID 0 issue in the last commit.

Can you try it out?

**Comment by liudasdd** [comment]
2020-11-26 14:33:15,246 - ERROR: NetBox returned: POST /api/ipam/vlans/ Bad Request
2020-11-26 14:33:15,246 - ERROR: NetBox returned body: {'vid': ['Ensure this value is greater than or equal to 1.']}
2020-11-26 14:33:15,246 - ERROR: Request Failed for VLAN. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}], 'name': 'C11', 'vid': 0, 'site': 1}
2020-11-26 14:33:17,620 - ERROR: Unable to determine second key 'virtual_machine' for virtual machine interface 'centos-7-template', got: None
2020-11-26 14:33:17,620 - ERROR: This could cause serious errors and lead to wrongly assigned object relations!!!

and this error repeats for all other VMs

Another type of error is this:
2020-11-26 14:33:35,657 - ERROR: NetBox returned: POST /api/ipam/vlans/ Bad Request
2020-11-26 14:33:35,657 - ERROR: NetBox returned body: {'vid': ['Ensure this value is greater than or equal to 1.']}
2020-11-26 14:33:35,657 - ERROR: Request Failed for VLAN. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-example'}], 'name': 'C11', 'vid': 0, 'site': 1}
2020-11-26 14:33:35,966 - ERROR: Unfortunately updated item untagged_vlan for object vNIC 1 (VM Network) (centos-7-template) could not be fully resolved: <NBVLAN instance '0 (XXX lab)' at 140426887350760>
2020-11-26 14:33:35,967 - ERROR: Unfortunately updated item untagged_vlan for object vNIC 1 (VM Network) (centos-8-template) could not be fully resolved: <NBVLAN instance '0 (XXX lab)' at 140426887350760>
2020-11-26 14:33:35,968 - ERROR: Unfortunately updated item untagged_vlan for object vNIC 1 (VM Network) (cleaf01) could not be fully resolved: <NBVLAN instance '0 (XXX lab)' at 140426887350760>

**Comment by bb-Ricardo** [comment]
Thank you for testing. 

These are VM interfaces with VLAN 0?

**Comment by liudasdd** [comment]
Yes,  all VMs are connected to the port group which VLAN ID: 0

**Comment by bb-Ricardo** [comment]
Ahh, will fix this tomorrow.

**Comment by liudasdd** [comment]
I know, quite unusual. But this is a lab environment, pardon me

**Comment by bb-Ricardo** [comment]
These are the cases i'm missing and it's perfect to have people like you with different setups. Everything shounld be covered. Also fixing this should be pretty straight forward.

**Comment by bb-Ricardo** [comment]
hey, can you give it a try and check if it solves your issue? It's in "next-release"

**Comment by liudasdd** [comment]
well, looks like there is no erros. Interface without vlans are correctly assigned with VLAN ID:0. Thanks!

**Comment by bb-Ricardo** [comment]
Awesome. Thank you for testing it again.
