### ISSUE TITLE
Getting some error related module "Packaging"

### ISSUE THREAD

**Issue by AnuragYewale15** [bb-Ricardo/netbox-sync#366]
Hi @bb-Ricardo ,
Traceback (most recent call last):
  File "/opt/netbox-sync/netbox-sync.py", line 21, in <module>
    from module.netbox.connection import NetBoxHandler
  File "/opt/netbox-sync/module/netbox/__init__.py", line 10, in <module>
    from module.netbox.object_classes import (
  File "/opt/netbox-sync/module/netbox/object_classes.py", line 14, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

Can you help me out

**Comment by bb-Ricardo** [comment]
Hi,

The module `packaging` is part of the requirements.txt file. Please make sure to followe the installation instructions and active your virtual environment before running netbox-sync.

**Comment by AnuragYewale15** [comment]
Thank You, There was some configuration issue on our side.
