### ISSUE TITLE
Vlans tagged even with sync disabled

### ISSUE THREAD

**Issue by rizlas** [bb-Ricardo/netbox-sync#392]
Hi,
I've currently disabled vlan sync in my settings and of course vlans are not synced anymore but they are still tagged every run.

**Comment by bb-Ricardo** [comment]
Hey,

Thanks for the issue. Will have a look at that.

**Comment by rizlas** [comment]
Hi, no problem at all.
I'll try on Monday.

**Comment by rizlas** [comment]
Monday is the friday 😆 

Im getting this error

```bash
./netbox-sync.py -c /settings/settings.ini -l DEBUG2
Traceback (most recent call last):
  File "/app/netbox-sync/./netbox-sync.py", line 23, in <module>
    from module.sources import instantiate_sources
  File "/app/netbox-sync/module/sources/__init__.py", line 11, in <module>
    from module.sources.vmware.connection import VMWareHandler
  File "/app/netbox-sync/module/sources/vmware/connection.py", line 29, in <module>
    from module.sources.common.source_base import SourceBase
  File "/app/netbox-sync/module/sources/common/source_base.py", line 22, in <module>
    class SourceBase:
  File "/app/netbox-sync/module/sources/common/source_base.py", line 182, in SourceBase
    def return_longest_matching_prefix_for_ip(self, ip_to_match=None, site_name=None) -> NBPrefix|None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by rizlas** [comment]
Ok I'm checking the docker image. Maybe the problem is the python version

**Comment by rizlas** [comment]
Friday is the new Monday 😆 
tested and all good, thanks!

**Comment by bb-Ricardo** [comment]
great, thank you very much for testing. Have a nice weekend.

**Comment by rizlas** [comment]
You too 👍🏻
