### ISSUE TITLE
UnboundLocalError: local variable 'ip' referenced before assignment

### ISSUE THREAD

**Issue by izheen** [bb-Ricardo/netbox-sync#4]
Very nice too see this project revived, thank you for your work!

Im trying to get this setup in our testing environment, we have been using the original project for a while. 

Im getting the following error when im trying to sync:

2020-11-13 10:47:02,966 - DEBUG2: Parsing vCenter VM: XX-XX-CRM
2020-11-13 10:47:02,985 - DEBUG2: Trying to find site name for cluster 'vSAN-HY'
2020-11-13 10:47:02,986 - DEBUG2: Found a match (vSAN-HY) for vSAN-HY, using site 'DC01'
2020-11-13 10:47:03,055 - DEBUG2: Found default IPv4 gateway 10.54.115.1
2020-11-13 10:47:03,055 - DEBUG2: Parsing device VirtualVmxnet3: 00:50:56:B2:D6:27
2020-11-13 10:47:03,062 - DEBUG2: Trying to find a virtual machine based on the collected name, cluster, IP and MAC addresses
2020-11-13 10:47:03,064 - DEBUG2: No exact match found. Trying to find virtual machine based on MAC addresses
2020-11-13 10:47:03,070 - DEBUG2: No match found. Trying to find virtual machine based on primary IP addresses
Traceback (most recent call last):
  File "netbox-sync.py", line 165, in <module>
    main()
  File "netbox-sync.py", line 146, in main
    source.apply()
  File "/opt/netbox-sync-dev/module/sources/vmware/connection.py", line 319, in apply
    view_details.get("view_handler")(obj)
  File "/opt/netbox-sync-dev/module/sources/vmware/connection.py", line 1510, in add_virtual_machine
    p_ipv4=vm_primary_ip4, p_ipv6=vm_primary_ip6)
  File "/opt/netbox-sync-dev/module/sources/vmware/connection.py", line 652, in add_device_vm_to_inventory
    device_vm_object = self.get_object_based_on_primary_ip(object_type, p_ipv4, p_ipv6)
  File "/opt/netbox-sync-dev/module/sources/vmware/connection.py", line 466, in get_object_based_on_primary_ip
    if _matches_device_primary_ip(grab(device, "data.primary_ip4"), primary_ip4) is True:
  File "/opt/netbox-sync-dev/module/sources/vmware/connection.py", line 447, in _matches_device_primary_ip
    if ip is not None and ip.split("/")[0] == ip_needle:
UnboundLocalError: local variable 'ip' referenced before assignment

The VM it self is not yet in Netbox, the set_primary_ip directive is set to always in settings.ini. Please advice, Thanks!

**Comment by bb-Ricardo** [comment]
Sorry, still a bug.

Already fixed this but was not able to push code yesterday.

currently testing with different vCenter versions. Even seems to work with a vCenter 5.5

will let you know as soon as I pushed the latest changes

**Comment by izheen** [comment]
No worries, great!

Thank you for letting me know

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a new commit which should be the first working beta. can you give it a go please and let me know about any issues/errors?

thank you.

**Comment by izheen** [comment]
Just did a re-sync now and everything synced nicely. Big suprise too see the VLANs from portgroups being synced which is great news!

I also checked if this issue from the original project was present: https://github.com/synackray/vcenter-netbox-sync/issues/114 but that seems to be gone which is also great news, it is no longer mixing them up!

Let me know if there is any function testing i can assist with, we have a sizeable environment to test with and have a test environment setup for netbox. Thanks again!

**Comment by bb-Ricardo** [comment]
great news, thank you for this feedback.

did you use the `cluster_site_relation` var and is it clear how to use it?

did you get any WARNINGS or ERRORS while syncing?

**Comment by izheen** [comment]
I checked the logs now and i have some warnings, i think they relate to the linked issue from the original project:

2020-11-16 13:43:27,909 - WARNING: Prefix vlan '407 (XXX)' does not match interface vlan '237 (XXX)' for 'vNIC 1 (XXX-vsan-hy) (XXXWP01)
2020-11-16 13:43:36,922 - WARNING: Prefix vlan '407 (XXX)' does not match interface vlan '405 (XXX)' for 'vNIC 1 (XXX-vsan-hy) (XXXEB01)
2020-11-16 13:43:46,406 - WARNING: Prefix vlan '407 (XXX)' does not match interface vlan '405 (XXX)' for 'vNIC 1 (XXX-vsan-hy) (XXXlab01)

We have multiple networks with the same IP prefixes, but they are on their own VLAN and their own VRF(firewall) in netbox and in reality.

Also have some more warnings relating to the firewalls we use and virtual ips added to them:

2020-11-16 13:43:52,917 - WARNING: IP prefix length of 'XXX.XXX.145.78/25' (vNIC 1 (PubCustNet2-100) (fw0065-dc01-XXX)) doesn't match network prefix length '24'! 

This relates to the way we add VIPs on the firewalls we use, the vips are usually added with a /32 or /25 in the firewall but the prefix in netbox is added with /24

So all warnings are related to how we do our config so they are all fine.

Regarding the cluster_site_relation i thought it was not super clear on how to do it(i also only set cluster_site_relation first and not the host one and i couldn't run the script, i needed them both which was not clear from the documentation), i saw in one of your issue threads an example: 192\.168\.20\..* = XYZ which cleared it up a bit, i would recommend adding a clearer example with the use of DNS name instead of IP since i would say that the most regular naming scheme of hosts in VMWare is by their DNS names.

Thanks!

**Comment by bb-Ricardo** [comment]
If the WARNINGS are ok for your setup then that is fine.

regarding cluster_site_relation: You should not need to set both if hosts are in exact the same NetBox site as the cluster.
I rephrased the config option to this:
```
# This option defines which vCenter cluster is part of a NetBox site. This is done
# with a comma separated key = value list.
#   key: defines the cluster name as regex
#   value: defines the NetBox site name
# This is a quite important config setting as IP addresses, prefixes, VLANs and
# VRFs are site dependent. In order to assign the correct prefix to an IP
# address it is important to pick the correct site.
# A VM always depends on the cluster site relation.
# cluster_site_relation = Cluser_NYC = New York , Cluster_FFM.* = Frankfurt

# Same as cluster site but on host level. If unset it will fall back
# to cluster_site_relation.
# host_site_relation = Cluser_NYC = New York, Cluster_FFM = Frankfurt
```
Please let me know what you think

**Comment by izheen** [comment]
Thanks, that looks good and clearer! You may close this one, thanks again

**Comment by bb-Ricardo** [comment]
great, thank you for the feedback
