### ISSUE TITLE
Problem with POST

### ISSUE THREAD

**Issue by biq-priplata** [bb-Ricardo/netbox-sync#46]
Ho i have problem with creating anything with this tool, Netbox latest version and netbox-sync lastest version of main

The problem started with creating site and with another: 
```
2021-02-17 14:52:55,705 - DEBUG2: Sending POST to 'http://localhost/api/dcim/sites/' with data 'b'{"name": "C4C", "slug": "c4c"}''.
2021-02-17 14:52:55,705 - DEBUG2: Received HTTP Status 200.
2021-02-17 14:52:55,705 - DEBUG2: Adding unresolved dependencies back to object: ['tags']
2021-02-17 14:52:55,705 - DEBUG2: Parsing 'site' data structure: None
2021-02-17 14:52:55,705 - DEBUG2: Compiling TAG list
2021-02-17 14:52:55,705 - DEBUG2: Parsing 'tag' data structure: None
2021-02-17 14:52:55,706 - INFO: Found unset key 'name' while parsing None. Skipping This key
2021-02-17 14:52:55,706 - DEBUG: Updated tag object: None
2021-02-17 14:52:55,706 - DEBUG2: Parsing 'tag' data structure: None
2021-02-17 14:52:55,706 - INFO: Found unset key 'name' while parsing None. Skipping This key
2021-02-17 14:52:55,706 - DEBUG: Updated tag object: None
Traceback (most recent call last):
  File "netbox-sync.py", line 143, in <module>
    main()
  File "netbox-sync.py", line 133, in main
    nb_handler.update_instance()
  File "/opt/netbox/netbox-sync/module/netbox/connection.py", line 696, in update_instance
    self.update_object(nb_object_sub_class)
  File "/opt/netbox/netbox-sync/module/netbox/connection.py", line 666, in update_object
    this_object.update(data=unresolved_dependency_data)
  File "/opt/netbox/netbox-sync/module/netbox/object_classes.py", line 369, in update
    new_value_str = str(new_value.get_display_name())
  File "/opt/netbox/netbox-sync/module/netbox/object_classes.py", line 754, in get_display_name
    return sorted([x.get_display_name() for x in self])
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by bb-Ricardo** [comment]
Hi,

well this should not happen.

Was this the first run?
Can you post more of the debug log? After log line: `First run, unset attributes if necessary.`

**Comment by biq-priplata** [comment]
Hi, 
sorry for this late message 
`2021-02-22 12:22:04,991 - DEBUG: First run, unset attributes if necessary.
2021-02-22 12:22:04,993 - DEBUG: Second run, update all items
2021-02-22 12:22:04,993 - INFO: Creating new NetBox 'tag' object 'NetBox-synced: Orphaned' with data: {'name': 'NetBox-synced: Orphaned', 'color': '607d8b', 'description': 'A source which has previously provided this object no longer states it exists. Objects would be automatically removed after 0 days but pruning is currently disabled.', 'slug': 'netbox-synced-orphaned'}
2021-02-22 12:22:04,993 - DEBUG2: Sending POST to 'http://localhost/api/extras/tags/' with data 'b'{"name": "NetBox-synced: Orphaned", "color": "607d8b", "description": "A source which has previously provided this object no longer states it exists. Objects would be automatically removed after 0 days but pruning is currently disabled.", "slug": "netbox-synced-orphaned"}''.
2021-02-22 12:22:05,009 - DEBUG2: Received HTTP Status 200.
2021-02-22 12:22:05,009 - INFO: Creating new NetBox 'tag' object 'NetBox-synced' with data: {'name': 'NetBox-synced', 'description': "Created and used by NetBox Sync Script to keep track of created items. DO NOT change this tag, otherwise syncing can't keep track of deleted objects.", 'slug': 'netbox-synced'}
2021-02-22 12:22:05,009 - DEBUG2: Sending POST to 'http://localhost/api/extras/tags/' with data 'b'{"name": "NetBox-synced", "description": "Created and used by NetBox Sync Script to keep track of created items. DO NOT change this tag, otherwise syncing can\'t keep track of deleted objects.", "slug": "netbox-synced"}''.
2021-02-22 12:22:05,018 - DEBUG2: Received HTTP Status 200.
2021-02-22 12:22:05,018 - INFO: Creating new NetBox 'tag' object 'Source: biq-old' with data: {'name': 'Source: biq-old', 'description': 'Marks sources synced from vCenter biq-old (10.1.250.2) to this NetBox Instance.', 'slug': 'source-biq-old'}
2021-02-22 12:22:05,019 - DEBUG2: Sending POST to 'http://localhost/api/extras/tags/' with data 'b'{"name": "Source: biq-old", "description": "Marks sources synced from vCenter biq-old (10.1.250.2) to this NetBox Instance.", "slug": "source-biq-old"}''.
2021-02-22 12:22:05,027 - DEBUG2: Received HTTP Status 200.
2021-02-22 12:22:05,028 - INFO: Creating new NetBox 'site' object 'vCenter: biq-old' with data: {'name': 'vCenter: biq-old', 'slug': 'vcenter-biq-old', 'comments': 'A default virtual site created to house objects that have been synced from this vCenter instance and have no predefined site assigned.'}
2021-02-22 12:22:05,028 - DEBUG2: Sending POST to 'http://localhost/api/dcim/sites/' with data 'b'{"name": "vCenter: biq-old", "slug": "vcenter-biq-old", "comments": "A default virtual site created to house objects that have been synced from this vCenter instance and have no predefined site assigned."}''.
2021-02-22 12:22:05,058 - DEBUG2: Received HTTP Status 200.
2021-02-22 12:22:05,058 - DEBUG2: Adding unresolved dependencies back to object: ['tags']
2021-02-22 12:22:05,058 - DEBUG2: Parsing 'site' data structure: None
2021-02-22 12:22:05,058 - DEBUG2: Compiling TAG list
2021-02-22 12:22:05,058 - DEBUG2: Parsing 'tag' data structure: None
2021-02-22 12:22:05,058 - INFO: Found unset key 'name' while parsing None. Skipping This key
2021-02-22 12:22:05,058 - DEBUG: Updated tag object: None
2021-02-22 12:22:05,058 - DEBUG2: Parsing 'tag' data structure: None
2021-02-22 12:22:05,058 - INFO: Found unset key 'name' while parsing None. Skipping This key
2021-02-22 12:22:05,058 - DEBUG: Updated tag object: None
Traceback (most recent call last):
  File "netbox-sync.py", line 143, in <module>
    main()
  File "netbox-sync.py", line 133, in main
    nb_handler.update_instance()
  File "/opt/netbox/netbox-sync/module/netbox/connection.py", line 696, in update_instance
    self.update_object(nb_object_sub_class)
  File "/opt/netbox/netbox-sync/module/netbox/connection.py", line 666, in update_object
    this_object.update(data=unresolved_dependency_data)
  File "/opt/netbox/netbox-sync/module/netbox/object_classes.py", line 369, in update
    new_value_str = str(new_value.get_display_name())
  File "/opt/netbox/netbox-sync/module/netbox/object_classes.py", line 754, in get_display_name
    return sorted([x.get_display_name() for x in self])
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
`
i trying uri localhost, ip where listen its same :/

**Comment by bb-Ricardo** [comment]
Hey, can you check out the latest "development" branch? I made changes to the "get_display_name()" method.

**Comment by biq-priplata** [comment]
Hi @bb-Ricardo 
Sorry for late reply, i have bad message to you the result its same :(.

**Comment by bb-Ricardo** [comment]
Thank you for testing. Will look into it

**Comment by bb-Ricardo** [comment]
hey, any luck with testing on newest versions or did you gave up? Cause I don't know why the script tries to create a tag where NetBox says it is already present (status 200 instead of 201).

**Comment by bb-Ricardo** [comment]
closing due to no feedback.
