### ISSUE TITLE
It does not create all devices in the same subnet, just create one randomly

### ISSUE THREAD

**Issue by jozefrebjak** [bb-Ricardo/netbox-sync#52]
I have two sources:

I don't have hosts added with DNS names only raw IP addresses.  

1. vCenter with hosts: (For customers)

10.99.105.101
10.99.105.102
10.99.105.103
10.99.105.104 - Spare (Not responding now)

2. vCenter with hosts: (Private)

10.99.105.105
19.99.105.106

When I run `./netbox-sync.py` it will not create all of them, but only one randomly and recreate VLANs, NICs, etc. 

It's the same when I use only the first source with hosts from .1 to .4

**Comment by jozefrebjak** [comment]
@bb-Ricardo  I'm going to switch branch and I will let you know.

**Comment by jozefrebjak** [comment]
@bb-Ricardo  I am now on the development branch and It seems does not work.

I cloned with ```git clone --single-branch --branch development https://github.com/bb-Ricardo/netbox-sync.git```

```
git status
On branch development
Your branch is up to date with 'origin/development'.
```

Do I need to edit some config? I used the previous one.

**Comment by bb-Ricardo** [comment]
A `git checkout development` would have been fine.

Can you run the script with `-l DEBUG2` and send me the whole output? My mail address can be found in the head of `netbox-sync.py`

**Comment by jozefrebjak** [comment]
> @bb-Ricardo Yes. I am working on it.

Sent

**Comment by bb-Ricardo** [comment]
can you d a `git pull` and run the script again. After that can you post `grep -i serial log/netbox-sync.log`? Thank you

**Comment by jozefrebjak** [comment]
@bb-Ricardo I've sent an email to you.

**Comment by jozefrebjak** [comment]
@bb-Ricardo I have created all of the IP addresses, but all are bound to the vmk0 interface of device 10.99.105.106

![Snímka obrazovky 2021-03-10 o 11 34 14](https://user-images.githubusercontent.com/36922215/110616247-a054ff80-8194-11eb-92c4-37db11073293.png)

**Comment by jozefrebjak** [comment]
> I sent you another mail.
> 
> I added a new config option "match_host_by_serial". You need to add this option to your config and need to set it to False.

I ran git pull and added ```match_host_by_serial = False```, but there some invalid syntax

```
Traceback (most recent call last):
  File "./netbox-sync.py", line 25, in <module>
    from module.sources import instantiate_sources
  File "/opt/netbox-sync/module/sources/__init__.py", line 11, in <module>
    from .vmware.connection import VMWareHandler
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 70
    "match_host_by_serial", True
                          ^
SyntaxError: invalid syntax
```

**Comment by bb-Ricardo** [comment]
you need to switch to master, delete "development" branch and pull it again

**Comment by jozefrebjak** [comment]
@bb-Ricardo  I deleted the whole directory, downloaded the development branch with `git clone --single-branch --branch development https://github.com/bb-Ricardo/netbox-sync.git` updated settings by adding `match_host_by_serial = False` to all my sources and ran `./netbox-sync.py` and now I'm getting invalid syntax

```
Traceback (most recent call last):
  File "./netbox-sync.py", line 25, in <module>
    from module.sources import instantiate_sources
  File "/opt/netbox-sync/module/sources/__init__.py", line 11, in <module>
    from .vmware.connection import VMWareHandler
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 972
    if device_vm_object is None and object_data.get("serial") is not None and
                                                                            ^

SyntaxError: invalid syntax
```

**Comment by jozefrebjak** [comment]
@bb-Ricardo It seems the patch is making it work. Now I have all of the devices added. 

**Thank you !**

**Comment by jozefrebjak** [comment]
@bb-Ricardo but it's look like it add IP addresses only to last one:

![Snímka obrazovky 2021-03-10 o 12 52 29](https://user-images.githubusercontent.com/36922215/110625268-7f45dc00-819f-11eb-83d5-1098f87327b6.png)

there is newly added device with no IP Addresses

![Snímka obrazovky 2021-03-10 o 12 52 59](https://user-images.githubusercontent.com/36922215/110625332-95ec3300-819f-11eb-9d81-900c38c79d9e.png)

Maybe I need to delete the devices with IP Addresses assignments.

**Comment by jozefrebjak** [comment]
@bb-Ricardo  I believe that I solved all my problems. We can close this issue.

**Comment by xth0331** [comment]
I also encountered a similar problem, Add parameter “match_host_by_serial = False ” still unresolved，
![image](https://user-images.githubusercontent.com/20889124/128017674-a905cc08-64eb-4aef-a63d-bf32feefe121.png)，

May be related to this
![image](https://user-images.githubusercontent.com/20889124/128017899-f16aa1bb-1982-461a-9c9b-99a8081363e9.png)

**Comment by bb-Ricardo** [comment]
@xth0331 You still having this issue even with `match_host_by_serial = False` off? Did you delete the IP addresses from the interface and tried again?
