### ISSUE TITLE
DNS Name Lookup not working

### ISSUE THREAD

**Issue by jozefrebjak** [bb-Ricardo/netbox-sync#53]
If I enable `dns_name_lookup = True` I am getting this error. What I am missing ?

```Traceback (most recent call last):
  File "./netbox-sync.py", line 143, in <module>
    main()
  File "./netbox-sync.py", line 125, in main
    inventory.query_ptr_records_for_all_ips()
  File "/opt/netbox-sync/module/netbox/inventory.py", line 347, in query_ptr_records_for_all_ips
    records = perform_ptr_lookups(data.get("ips"), data.get("servers"))
  File "/opt/netbox-sync/module/common/support.py", line 143, in perform_ptr_lookups
    results = loop.run_until_complete(queue)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/netbox-sync/module/common/support.py", line 173, in reverse_lookup
    response = await resolver.gethostbyaddr(ip)
AttributeError: 'DNSResolver' object has no attribute 'gethostbyaddr'```

**Comment by bb-Ricardo** [comment]
Hey, did you install all dependencies accordingly?

Cause aiodns should have this method. 🤔

**Comment by jozefrebjak** [comment]
I did what you mentioned in README.md

```
sudo apt-get install virtualenv
cd /opt
git clone https://github.com/bb-Ricardo/netbox-sync.git
cd netbox-sync
virtualenv -p python3 .env
. .env/bin/activate
pip3 install -r requirements.txt
```

**Comment by jozefrebjak** [comment]
Do i need to run netbox-sync.py from ``. .env/bin/activate`` ?
