### ISSUE TITLE
Handle missing "API-Version" HTTP header properly

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#57]
Hi!
help me please. i don't start this script
How fix it  ? 

(venv) root@netbox:/opt/netbox/scripts/netbox-sync/module/netbox# python3 /opt/netbox/scripts/netbox-sync/netbox-sync.py
2021-04-15 17:39:00,595 - INFO: Starting NetBox Sync
Traceback (most recent call last):
  File "/opt/netbox/scripts/netbox-sync/netbox-sync.py", line 143, in <module>
    main()
  File "/opt/netbox/scripts/netbox-sync/netbox-sync.py", line 82, in main
    nb_handler = NetBoxHandler(settings=netbox_settings, inventory=inventory)
  File "/opt/netbox/scripts/netbox-sync/module/netbox/connection.py", line 99, in __init__
    api_version = self.get_api_version()
  File "/opt/netbox/scripts/netbox-sync/module/netbox/connection.py", line 217, in get_api_version
    result = str(response.headers["API-Version"])
  File "/opt/netbox/scripts/vcenter-netbox-sync/venv/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'api-version'

**Comment by Sivolen** [comment]
Iam fix this problem, problem was in nginx, nginx don’t  redirect to https with http

**Comment by bb-Ricardo** [comment]
Hi,

I still need to fix the issue that the tool doesn't through an exception if the NetBox version can not be found.
