### ISSUE TITLE
Error on running script

### ISSUE THREAD

**Issue by mleonc1977** [bb-Ricardo/netbox-sync#80]
Hello, running the script on my environment stops at this:

Traceback (most recent call last):
  File "netbox-sync.py", line 143, in <module>
    main()
  File "netbox-sync.py", line 119, in main
    source.apply()
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 394, in apply
    view_details.get("view_handler")(obj)
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 1621, in add_host
    pgroup_nics = nic_order.activeNic + nic_order.standbyNic
AttributeError: 'NoneType' object has no attribute 'activeNic'

Would it be that a VM has no NIC assign or what?

Thanks!

**Comment by bb-Ricardo** [comment]
Hi, this is what it looks like.

Will take care of it once I'm back from holidays.

For now you could just exclude this vm via config.

**Comment by mleonc1977** [comment]
Sure! thanks for your time!

**Comment by bb-Ricardo** [comment]
Will add fix to the new release. Can you test it please?
